// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVGyAmud1s4OtIF2Q_IiB8NKk0LzCLGTI',
    appId: '1:620232038288:web:3d0c6368837d7de2b00515',
    messagingSenderId: '620232038288',
    projectId: 'inventariores-6d31d',
    authDomain: 'inventariores-6d31d.firebaseapp.com',
    storageBucket: 'inventariores-6d31d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBncE1NZys5yvoprR8yi3oOjRvJSE021cg',
    appId: '1:620232038288:android:d6cc49e97df5d64fb00515',
    messagingSenderId: '620232038288',
    projectId: 'inventariores-6d31d',
    storageBucket: 'inventariores-6d31d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk9dKYd1rU6-rmIZFpr06eUFFTVYsiO7s',
    appId: '1:620232038288:ios:51dce547de06ab75b00515',
    messagingSenderId: '620232038288',
    projectId: 'inventariores-6d31d',
    storageBucket: 'inventariores-6d31d.firebasestorage.app',
    iosBundleId: 'com.example.heris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk9dKYd1rU6-rmIZFpr06eUFFTVYsiO7s',
    appId: '1:620232038288:ios:51dce547de06ab75b00515',
    messagingSenderId: '620232038288',
    projectId: 'inventariores-6d31d',
    storageBucket: 'inventariores-6d31d.firebasestorage.app',
    iosBundleId: 'com.example.heris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVGyAmud1s4OtIF2Q_IiB8NKk0LzCLGTI',
    appId: '1:620232038288:web:a4a17d10820642f1b00515',
    messagingSenderId: '620232038288',
    projectId: 'inventariores-6d31d',
    authDomain: 'inventariores-6d31d.firebaseapp.com',
    storageBucket: 'inventariores-6d31d.firebasestorage.app',
  );
}
